## files
library(Matrix)
library(Hmisc)
library(parallel)
library(texreg)
source("AdjustValue.R")
source("CheckUB.R")
source("ConvParam.R")
source("MakeCovariatesUtilStr.R")
source("MakeCovariatesAll.R")
source("MakePolyLD.R")
source("CalcLikelihoodType.R")
source("CalcLikelihoodYS.R")
source("CalcLikelihoodY.R")
source("CalcLikelihoodCCP.R")
source("CalcLikelihoodAll.R")
source("CalcPLTakeUp.R")
source("UpdateState.R")
source("UpdateXbar.R")
source("UpdateEM.R")
source("UpdateSVFI.R")
source("CalcUtil.R")
source("SampleStateVariables.R")
source("MakeProfile.R")
source("MakeTransitionMatrix.R")
source("SimulateChoice.R")
source("SimulateStrModelCore.R")
source("SimulateStrModel.R")
source("SimulateProfile.R")
source("PrepSVFI.R")
source("CalcCcpEmax.R")
source("TakeAveList.R")

source("SolveForPolicy.R")
source("CalcMeanOutcomes.R")

matmul.Xb <- function(X,b) (X %*% b)[,1]

## load CSV data (change appropriately)
jpsc <- read.csv("../../data/180328a/jpsc180328a.csv")
